### ISSUE TITLE
Increasing training time of a2c

### ISSUE THREAD

**Issue by qxwsniff** [thu-ml/tianshou#140]
I use the example of pong_a2c.py to train on my own env, and I find that the training time increasing after each epoch?
Is there any way to improve it?

**Comment by Trinkle23897** [comment]
It is because that the current mechanism of collector is to play a full episode and save them into the buffer. The increasing of training time may be due to the enhancement of policy, thus the length per episode will go up, so that the entire epoch will also increase.

Two possible solutions:
1. increasing the epoch length
2. modify the on-policy trainer (it is not complex at all)
