### ISSUE TITLE
Readme example test cannot run into 3s

### ISSUE THREAD

**Issue by Nillouise** [thu-ml/tianshou#196]
I use this test run in my PC 2700x + 2060, it cost 10s rather than 3s, and I run this test in only cpu without cuda, it's perfomance only change a little. The cuda version test and cpu version test both use about 10s.

python3 test/discrete/test_pg.py --seed 0 --render 0.03

I am new to cuda and machine learning, but the system linux mint is fresh install, and the torch.cuda.is_available()  is True

**Comment by Trinkle23897** [comment]
It depends on seed. 
- Different torch version can generate different results even on the same machine with same seed.
- Even the seed is fixed, the result can be different under different machine configure. I tested with two ubuntu18.04 with different GPU (one 1060 and the other is 2080Ti), the results were different.

Thus I said “seed may be different in your configuration”

**Comment by Nillouise** [comment]
But 3s compare to 10s is a big difference, it make the benmark nonsense.

**Comment by Trinkle23897** [comment]
3s is one of these runs. In order to make the benchmark result comparable, we use several runs to reduce the wall-time variance. You can see in the table:
![2020-08-31 15-22-11 的屏幕截图](https://user-images.githubusercontent.com/8189182/91693644-edc93200-eb9d-11ea-91e3-e2ccf76027a2.png)
10s is near the average.
