### ISSUE TITLE
About the implementation of A2C.

### ISSUE THREAD

**Issue by dxu23nc** [thu-ml/tianshou#243]
Hi, 

Recently, I am using Tianshou to test the A2C algorithm. I want to ask something about the implementation.
In tianshou, does it only preserve one copy of the policy in the GPU?  In each step, new states are collected into one big batch. Then that batch was split into small batches and Each small batch will update the network once. 
I am pretty confused about this. Is this the same workflow as the original A2C?

**Comment by Trinkle23897** [comment]
Because A2C is in sync mode, only one copy of the policy needs to be maintained.
Currently it is a little difference between our implementation and the original A2C, because the original A2C does not finish the whole episode and do a network update, instead they perform a fixed number of env steps and split the whole episode into many small pieces to the network training: suppose we have an episode with length of 10 and we update with batchsize=3
```
origin: [step1 step2 step3 comp_return(1~3) train(1~3) step4 step5 step6 comp_return(4~6) train(4~6) step7 step8 step9 comp_return(7~9) train(7~9) step10]
our: [step1 step2 step3 step4 step5 step6 step7 step8 step9 step10 comp_return(1~10) train(1~3) train(4~6) train(7~9)]
```
This will be fixed soon.

**Comment by dxu23nc** [comment]
After each step, there should have an inference for action selection. 
Actually, I am curious about keeping only one copy of the policy. Does this setting require that every worker should synchronize after each step to get a big "batch"?

**Comment by Trinkle23897** [comment]
Yep. A2C is the sync version of A3C (async version)
