### ISSUE TITLE
One question about GAE computation

### ISSUE THREAD

**Issue by lastditch222** [thu-ml/tianshou#348]
It seems that the computation of GAE is not based on the full episode (as the usual computation) because the sampled batch indexes from the buffer are not continuous from one episode.  I am not clear about this point. Thanks.

**Comment by ChenDRAG** [comment]
Indeed you are right. There are some usually seen scenarios where navie compution of GAE based on full episodes may lead to less accurate calculation. For instance, in on policy algorithm, we know classic method of sampling data is to run a full episode and then update based on full-episode data. But what if I want to sample 500 timesteps (may contain 2 full episodes and one truncated episode) and need to calculate advantage using GAE?
Tianshou's method to deal with this is by using bootstrap. It automatically detect that truncated episode and will regard the last step as a final step(`done` == True), but when bootstraping, it will still calculate v(`obs_next`) so that the estimate of previous timesteps are more accurate.
This is a bit more complex when you deal with multiple truncated episodes collected by multiple env_workers, but general idea is the same. All of these tricks/problems are naturally supported/handled by Tianshou.

**Comment by Trinkle23897** [comment]
In fact, this is the standard approach in most RL libraries.

**Comment by lastditch222** [comment]
@Trinkle23897 @ChenDRAG Hello, my question is that the sampled index is not continuous instead of truncated. For example, we may sample indexes [1, 3, 5, 20] from one episode or multiple episodes. Due to the discontinuous indexes, the power of gamma needs to consider the index interval while gamma in "_gae_return" function seems for continuous index sequence.

**Comment by ChenDRAG** [comment]
Sampled index is continuous actually(in a certain way), when you sample data using buffer's API `sample(0)`. `sample` method in Buffer will reorganise data to a sequence for you.

**Comment by Trinkle23897** [comment]
It should not happen in the current codebase. You can see GAE is only used in `onpolicy_trainer`, and it only supports `buffer.sample(0)`, which extract all data in the buffer.

**Comment by lastditch222** [comment]
Ok, thanks for the reply.
