### ISSUE TITLE
Some questions about RNN agent

### ISSUE THREAD

**Issue by M1ddlzh** [thu-ml/tianshou#355]
- [ ] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [ ] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [x] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  # 0.4.1 1.5.0+cpu 1.18.4 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)] win32
  ```

I have some questions about RNN implementation in v0.4.1. I can't find RecurrentActor in tianshou.utils.net.continuous, and why does RecurrentCritic not receive the hidden state?

**Comment by Trinkle23897** [comment]
> I can't find RecurrentActor in tianshou.utils.net.continuous

https://github.com/thu-ml/tianshou/blob/v0.4.1/tianshou/utils/net/continuous.py#L201-L324

RecurrentActor is the same as Recurrent: https://github.com/thu-ml/tianshou/blob/v0.4.1/tianshou/utils/net/common.py#L200-L257 -- see [test_drqn.py](https://github.com/thu-ml/tianshou/blob/v0.4.1/test/discrete/test_drqn.py)


> why does RecurrentCritic not receive the hidden state?

Because critic only measures whether a state is good or not. Only actor which is needed for decision-making that requires a hidden state. (think about the test phase, the policy only uses actor instead of both actor and critic)
Actually the state which critic received is a stacked observation during training if you use `stack_num` option in replay buffer. So that there's no need for critic to receive extra hidden state.

**Comment by M1ddlzh** [comment]
I confuse why you use hidden state in drqn, but you don't do the same for critic? They are all used to evaluate the value of state. If I don't use ```stack_num```, or ```stack_num=1```, do I need a hidden state?
Thanks!

**Comment by Trinkle23897** [comment]
No I mean in the evaluation, we don't use critic network, instead we only use actor network. Therefore hidden state is only essential for actor.

> If I don't use stack_num, or stack_num=1, do I need a hidden state?

You can still use hidden state in this setting. Just try to put something in `return Batch(state=...)` and see what it would receive in the next hidden state.
