### ISSUE TITLE
np.stack failing with Batch of np.array

### ISSUE THREAD

**Issue by externalsupplierstaff** [thu-ml/tianshou#392]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] RL algorithm bug
    + [ ] documentation request (i.e. "X is missing from the documentation.")
    + [ ] new feature request
- [x] I have visited the [source website](https://github.com/thu-ml/tianshou/)
- [x] I have searched through the [issue tracker](https://github.com/thu-ml/tianshou/issues) for duplicates
- [x] I have mentioned version numbers, operating system and environment, where applicable:
  ```python
  import tianshou, torch, numpy, sys
  print(tianshou.__version__, torch.__version__, numpy.__version__, sys.version, sys.platform)
  v0.4.2 1.8.1 1.20.1 3.8.10 (default, May 19 2021, 13:12:57) [MSC v.1916 64 bit (AMD64)] win32
  ```

I have an environment output which is a `ts.data.Batch` with keys "state" and "past_actions". However, in `tianshou.env.venvs.py line 245` I find the output unexpected. 
To reproduce:

```python
import tianshou as ts
import numpy as np
np.random.seed(0)

n_envs = 4
states_for_each_environment = [np.random.rand(224, 224, 3) for i in range(n_envs)]
past_actions_for_each_environment = [np.random.randint(0, 7, size=50) for i in range(n_envs)]

obs_list = tuple((ts.data.Batch(state=states_for_each_environment[i], past_actions=past_actions_for_each_environment[i]) for i in range(n_envs)))

# try:
obs_stack = np.stack(obs_list)
# except ValueError:
    # obs_stack = np.array(obs_list, dtype=object)


print('shapes')
print('actual shape:', obs_stack.shape)
print('except shape:', np.array(obs_list, dtype=object).shape)
print('desired shape:', '[(4, 224, 224, 3), (4, 50)]')
```

am I doing something wrong?

**Comment by Trinkle23897** [comment]
`ts.data.Batch(obs_list)` works fine... I'll take a look later to see what happened.

**Comment by externalsupplierstaff** [comment]
Indeed! `ts.data.Batch(obs_list)` does the trick! 

maybe a hotfix like

```python
        ### START HOTFIX
        if type(obs_list[0]) is Batch:
            obs = Batch(obs_list)
        else:
            try:
                obs = np.stack(obs_list)
            except ValueError:  # different len(obs)
                obs = np.array(obs_list, dtype=object)
        # try:
        #     obs = np.stack(obs_list)
        # except ValueError:  # different len(obs)
        #     obs = np.array(obs_list, dtype=object)
        ### END HOTFIX
```

both in `BaseVectorEnv.step` and in `BaseVectorEnv.reset` is enough.

It was enough for me :)

**Comment by Trinkle23897** [comment]
1. The expected shape is `(4,)` since `(4, 224, 224, 3)` != `(4, 50)`. However, if you use `Batch(state, past_actions)`, its shape would be min(`(4, 224, 224, 3)`, `(4, 50)`) = `(4, 50)`. That's an expected behavior.
2. `np.array` will recursively converts elements to `dtype=object` numpy array if the object has `__getitem__`, so that if you use `np.array([Batch(np.array(...), np.array(...)), Batch(np.array(...), np.array(...))])`, it will be np.array over np.array, with both dtype=object.
3. `Batch(np.array of np.array)` cannot automatically convert to Batch, instead, `Batch(np.array/list of Batch/dict)` can. So that's why the result looks strange.
4. To resolve this issue, you can just change Batch to dict: `obs_list = tuple({"state":states_for_each_environment[i], "past_actions":past_actions_for_each_environment[i]} for i in range(n_envs))`. It is because `dict` doesn't have `__getitem__` attribute, so `np.array(list of dict)` would not automatically convert to np.array of np.array.

**Comment by Trinkle23897** [comment]
In short, change
```python
obs_list = tuple(Batch(...) ...)
```
to 
```python
obs_list = tuple(dict(...) ...)
```
