### ISSUE TITLE
Is there any example for SAC for discrete

### ISSUE THREAD

**Issue by yhisme** [thu-ml/tianshou#71]
Hi ,i search over all the project ,but i have not find any example for SAC discrete, how can i build it?or could you please add an example for SAC discrete

**Comment by Trinkle23897** [comment]
Yes, I'll implement soon.

**Comment by szrlee** [comment]
If you are going to implement the discrete version of SAC,
I suggest also making a try to save the probability of behavior policy \pi_t(a|s) on the sample trajectory and augment log(\pi/\pi_t) to the reward instead of the sampled entropy \log(\pi) term.
We found that multi-step divergence augmentation is better than (multi-step) augmented entropy formulation in our algorithmic framework (not the same as the SAC algorithm framework).

**Comment by yhisme** [comment]
ok thank you very much!:)
